import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { createReadStream } from 'node:fs';
import { access, mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, join, normalize, resolve, sep } from 'node:path';
import { Readable } from 'node:stream';
import { Env } from '@/config/env.schema';
import { StorageService } from './storage.service';

/**
 * Local disk implementation, rooted at STORAGE_ROOT.
 *
 * Keys are generated by the server, never taken from an upload's filename, but they are
 * still validated here: a storage layer that can be talked into writing outside its root
 * is a directory-traversal bug waiting for its first careless caller.
 */
@Injectable()
export class LocalDiskStorageService implements StorageService {
  private readonly logger = new Logger(LocalDiskStorageService.name);
  private readonly root: string;

  constructor(config: ConfigService<Env, true>) {
    this.root = resolve(config.get('STORAGE_ROOT', { infer: true }));
  }

  async save(key: string, buffer: Buffer, _mimeType: string): Promise<void> {
    const path = this.resolveKey(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, buffer);
  }

  async read(key: string): Promise<Readable> {
    return createReadStream(this.resolveKey(key));
  }

  async delete(key: string): Promise<void> {
    await rm(this.resolveKey(key), { force: true });
  }

  async exists(key: string): Promise<boolean> {
    try {
      await access(this.resolveKey(key));
      return true;
    } catch {
      return false;
    }
  }

  private resolveKey(key: string): string {
    if (isAbsolute(key)) {
      throw new Error(`storage key must be relative, got "${key}"`);
    }

    const path = resolve(join(this.root, normalize(key)));

    if (path !== this.root && !path.startsWith(this.root + sep)) {
      throw new Error(`storage key escapes the storage root: "${key}"`);
    }

    return path;
  }
}
